---
name: File-CachingFind
version: 0.66
author:
  - 'Thomas Dorner <Thomas.Dorner@start.de> or <Thomas.Dorner@gmx.de>'
abstract: find files within cached search paths (e.g. include files)
license: perl
requires:
  perl: 5.6.0
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  File::CachingFind:
    file: lib/File/CachingFind.pm
    version: 0.66
generated_by: Module::Build version 0.26
