--- #YAML:1.0
name:                File-CachingFind
version:             0.64
abstract:            find files within cached search paths (e.g. include files)
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Thomas Dorner <dorner (AT) pause.org>
