---
abstract: 'find files within cached search paths (e.g. include files)'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-CachingFind
provides:
  File::CachingFind:
    file: lib/File/CachingFind.pm
    version: 0.67
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.67
